export const CREATE_ROUTE_SERVICE = Symbol('CREATE_ROUTE_SERVICE');
export const UPDATE_ROUTE_SERVICE = Symbol('UPDATE_ROUTE_SERVICE');
export const DELETE_ROUTE_SERVICE = Symbol('DELETE_ROUTE_SERVICE');
export const ADD_BOXS_TO_ROUTE_SERVICE = Symbol('ADD_BOXS_TO_ROUTE_SERVICE');
export const REMOVE_BOXS_FROM_ROUTE_SERVICE = Symbol(
  'REMOVE_BOXS_FROM_ROUTE_SERVICE',
);
export const GET_ROUTERS_SERVICE = Symbol('GET_ROUTERS_SERVICE');
export const FIND_ALL_ROUTERS_SERVICE = Symbol('FIND_ALL_ROUTES_SERVICE');
export const ROUTE_REPOSITORY = Symbol('ROUTE_REPOSITORY');
