export const CREATE_ROUTE_SERVICE = Symbol('CREATE_ROUTE_SERVICE');
export const ADD_BOXS_TO_ROUTE_SERVICE = Symbol('ADD_BOXS_TO_ROUTE_SERVICE');
export const REMOVE_BOXS_FROM_ROUTE_SERVICE = Symbol(
  'REMOVE_BOXS_FROM_ROUTE_SERVICE',
);
export const GET_ROUTERS_SERVICE = Symbol('GET_ROUTERS_SERVICE');
export const ROUTE_REPOSITORY = Symbol('ROUTE_REPOSITORY');
