export const CONFIG_REPOSITORY = Symbol('CONFIG_REPOSITORY');
export const CREATE_CONFIG_SERVICE = Symbol('CREATE_CONFIG_SERVICE');
export const UPDATE_CONFIG_SERVICE = Symbol('UPDATE_CONFIG_SERVICE');
export const DELETE_CONFIG_SERVICE = Symbol('DELETE_CONFIG_SERVICE');
export const GET_CONFIGS_SERVICE = Symbol('GET_CONFIGS_SERVICE');
export const GET_CONFIG_BY_ID_SERVICE = Symbol('GET_CONFIG_BY_ID_SERVICE');
export const GET_CONFIG_BY_KEY_SERVICE = Symbol('GET_CONFIG_BY_KEY_SERVICE');
