export const CREATE_OCCURRENCE_SERVICE = Symbol('CREATE_OCCURRENCE_SERVICE');
export const OCCURRENCE_REPOSITORY = Symbol('OCCURRENCE_REPOSITORY');
export const CANCEL_OCCURRENCE_SERVICE = Symbol('CANCEL_OCCURRENCE_SERVICE');
export const APPROVE_OCCURRENCE_SERVICE = Symbol('APPROVE_OCCURRENCE_SERVICE');
export const GET_OCCURRENCE_SERVICE = Symbol('GET_OCCURENCE');

// Occurrence Type Symbols
export const OCCURRENCE_TYPE_REPOSITORY = Symbol('OCCURRENCE_TYPE_REPOSITORY');
export const CREATE_OCCURRENCE_TYPE_SERVICE = Symbol(
  'CREATE_OCCURRENCE_TYPE_SERVICE',
);
export const UPDATE_OCCURRENCE_TYPE_SERVICE = Symbol(
  'UPDATE_OCCURRENCE_TYPE_SERVICE',
);
export const DELETE_OCCURRENCE_TYPE_SERVICE = Symbol(
  'DELETE_OCCURRENCE_TYPE_SERVICE',
);
export const GET_OCCURRENCE_TYPES_SERVICE = Symbol(
  'GET_OCCURRENCE_TYPES_SERVICE',
);
export const GET_OCCURRENCE_TYPE_BY_ID_SERVICE = Symbol(
  'GET_OCCURRENCE_TYPE_BY_ID_SERVICE',
);
