export const CREATE_OCCURRENCE_SERVICE = Symbol('CREATE_OCCURRENCE_SERVICE');
export const OCCURRENCE_REPOSITORY = Symbol('OCCURRENCE_REPOSITORY');
export const CANCEL_OCCURRENCE_SERVICE = Symbol('CANCEL_OCCURRENCE_SERVICE');
export const APPROVE_OCCURRENCE_SERVICE = Symbol('APPROVE_OCCURRENCE_SERVICE');
export const GET_OCCURRENCE_SERVICE = Symbol('GET_OCCURENCE');
