export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const CREATE_USER_SERVICE = Symbol('CREATE_USER_SERVICE');
export const UPDATE_USER_SERVICE = Symbol('UPDATE_USER_SERVICE');
export const FIND_USERS_BY_FILTERS_SERVICE = Symbol(
  'FIND_USERS_BY_FILTERS_SERVICE',
);
