export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const CREATE_USER_SERVICE = Symbol('CREATE_USER_SERVICE');
export const UPDATE_USER_SERVICE = Symbol('UPDATE_USER_SERVICE');
export const FIND_USERS_BY_FILTERS_SERVICE = Symbol(
  'FIND_USERS_BY_FILTERS_SERVICE',
);
export const FIND_USER_BY_ID_SERVICE = Symbol('FIND_USER_BY_ID_SERVICE');
export const UPDATE_MY_PASSWORD_SERVICE = Symbol('UPDATE_MY_PASSWORD_SERVICE');
export const TOGGLE_USER_SERVICE = Symbol('TOGGLE_USER_SERVICE');
export const DELETE_USER_SERVICE = Symbol('DELETE_USER_SERVICE');
