export const LOGIN_USER_SERVICE = Symbol('LOGIN_USER_SERVICE');
export const SHOW_MY_USER_SERVICE = Symbol('SHOW_MY_USER_SERVICE');
export const REFRESH_TOKENS_SERVICE = Symbol('REFRESH_TOKENS_SERVICE');
