export const BOX_REPOSITORY = Symbol('BOX_REPOSITORY');
export const CREATE_BOX_SERVICE = Symbol('CREATE_BOX_SERVICE');
export const UPDATE_BOX_SERVICE = Symbol('UPDATE_BOX_SERVICE');

export const GET_BOX_BY_ID_SERVICE = Symbol('GET_BOX_BY_ID_SERVICE');
export const GET_BOX_SUMMARY_SERVICE = Symbol('GET_BOX_SUMMARY_SERVICE');
export const GET_BOXES_WITH_LABEL_AND_LOCATION_BY_LAT_LONG_MIN_MAX_AND_FILTERS =
  Symbol('GET_BOXES_WITH_LABEL_AND_LOCATION_BY_LAT_LONG_MIN_MAX_AND_FILTERS');
  export const DELETE_BOX_SERVICE = Symbol("DELETE_BOX_SERVICE")
