export const BOX_REPOSITORY = Symbol('BOX_REPOSITORY');
export const CREATE_BOX_SERVICE = Symbol('CREATE_BOX_SERVICE');
export const UPDATE_BOX_SERVICE = Symbol('UPDATE_BOX_SERVICE');
export const GET_BOXES_WITH_LOCATION_AND_LABEL_SERVICE = Symbol(
  'GET_BOXES_WITH_LOCATION_AND_LABEL_SERVICE',
);
export const GET_BOX_BY_ID_SERVICE = Symbol('GET_BOX_BY_ID_SERVICE');
