export const CREATE_BOX_SERVICE = Symbol('CREATE_BOX_SERVICE');
export const BOX_REPOSITORY = Symbol('BOX_REPOSITORY');
export const GET_ALL_BOXS_SERVICE = Symbol('GET_ALL_BOXS_SERVICE');
export const UPDATE_BOX_SERVICE = Symbol('UPDATE_BOX_SERVICE');
export const GET_SUMMARY_BOX = Symbol('GET_SUMMARY_BOX');
export const DELETE_BOX = Symbol('DELETE_BOX');
export const IMAGE_PROCESSING_SERVICE = Symbol('IMAGE_PROCESSING_SERVICE');

export const ROUTE_REPOSITORY = Symbol('ROUTE_REPOSITORY');
export const CREATE_ROUTE_BOX_SERVICE = Symbol('CREATE_BOX_ROUTE_SERVICE');
export const GET_ROUTE_BY_ID_SERVICE = Symbol('GET_ALL_BOX_ROUTE_SERVICE');
export const REMOVE_BOX_FOR_ROUTE_SERVICE = Symbol(
  'REMOVE_BOX_FOR_ROUTE_SERVICE',
);
export const ADD_BOX_FOR_ROUTE_SERVICE = Symbol('ADD_BOX_FOR_ROUTE_SERVICE');
export const DELETE_ROUTE_BY_ID_SERVICE = Symbol('DELETE_ROUTE_BY_ID_SERVICE');
export const GET_ALL_ROUTE_SERVICE = Symbol('GET_ALL_ROUTE_SERVICE');
