export const CREATE_USER_SERVICE = Symbol('CREATE_USER_SERVICE');
export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const UPDATE_USER_SERVICE = Symbol('UPDATE_USER_SERVICE');
export const GET_USER_BY_ID_SERVICE = Symbol('CREATE_USER_SERVICE');
export const TOGGLE_USER_SERVICE = Symbol('TOGGLE_USER_SERVICE');
