export const USER_REPOSITORY = 'USER_REPOSITORY';
export const CREATE_USER_SERVICE = 'CREATE_USER_SERVICE';
export const UPDATE_USER_SERVICE = 'UPDATE_USER_SERVICE';
export const GET_USER_BY_ID_SERVICE = 'GET_USER_BY_ID_SERVICE';
export const TOGGLE_USER_SERVICE = 'TOGGLE_USER_SERVICE';
export const UPDATE_FIREBASE_ID_SERVICE = 'UPDATE_FIREBASE_ID_SERVICE';
